pipeline:
  docker_tor:
    group: build
    image: plugins/docker
    dockerfile: tor/Dockerfile
    context: hugo
    repo: registry.quan.io/dan/tor
    registry: registry.quan.io
    secrets: [ docker_username, docker_password ]
    branches: [ master ]
    tags:
      - latest
      - "${DRONE_COMMIT_SHA:0:8}"
  docker_hugo:
    group: build
    image: plugins/docker
    dockerfile: hugo/Dockerfile
    context: hugo
    repo: registry.quan.io/dan/hugo
    registry: registry.quan.io
    secrets: [ docker_username, docker_password ]
    branches: [ master ]
    tags:
      - latest
      - "${DRONE_COMMIT_SHA:0:8}"
  docker_golang:
    group: build
    image: plugins/docker
    dockerfile: golang-testing/Dockerfile
    context: golang-testing
    repo: registry.quan.io/dan/golang-testing
    registry: registry.quan.io
    secrets: [ docker_username, docker_password ]
    branches: [ master ]
    tags:
      - latest
      - "${DRONE_COMMIT_SHA:0:8}"
  docker_goplayspace:
    group: build
    image: plugins/docker
    dockerfile: go-playspace/Dockerfile
    context: go-playspace
    repo: registry.quan.io/dan/go-playspace
    registry: registry.quan.io
    secrets: [ docker_username, docker_password ]
    branches: [ master ]
    tags:
      - latest
      - "${DRONE_COMMIT_SHA:0:8}"
