kind: pipeline
name: elixir

steps:
- name: docker - elixir
  image: plugins/docker
  settings:
    repo: reg.quan.io/dan/elixir
    tags:
      - latest
      - "1.9"
      - ${DRONE_COMMIT_SHA}
    dockerfile: elixir/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: reg.quan.io
---
kind: pipeline
name: tor

steps:
- name: docker - tor
  image: plugins/docker
  settings:
    repo: reg.quan.io/dan/tor
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    dockerfile: tor/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: reg.quan.io
---
kind: pipeline
name: golang

steps:
- name: docker - golang - testing
  image: plugins/docker
  settings:
    repo: reg.quan.io/dan/golang-testing
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    dockerfile: golang-testing/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: reg.quan.io
