kind: pipeline
name: default

- name: docker  
  image: plugins/docker
  settings:
    repo: reg.quan.io/dan/elixir
    tags:
      - latest
      - "1.9"
      - $DRONE_COMMIT_SHA 
    dockerfile: elixir/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

