name: Docker
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build
    - name: Login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}



# workflow "Build and Publish" {
#   on = "push"
# }

# action "Build" {
#   runs = "make"
#   args = "build"
# }

# action "Publish Filter" {
#   needs = ["Build"]
#   uses = "actions/bin/filter@master"
#   args = "branch master"
# }

# action "Docker Login" {
#   needs = ["Publish Filter"]
#   uses = "actions/docker/login@master"
#   secrets = ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
# }
